apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: laptop-svc
      port:
        number: 80
  tls:
  - hosts: 
    - "acfcf576f5f34498c9380ff7df15f9b5-9020de9ec6affdae.elb.eu-west-3.amazonaws.com"
    secretName: testsecret-tls  
  rules:
    - host: "acfcf576f5f34498c9380ff7df15f9b5-9020de9ec6affdae.elb.eu-west-3.amazonaws.com"
      http:
        paths:
        - path: /mobile
          pathType: Prefix
          backend:
            service:
              name: mobile-svc
              port:
                number: 80
        - path: /laptop
          pathType: Prefix
          backend:
            service:
              name: laptop-svc
              port:
                number: 80